# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package.json and install dependencies (including dev for build)
COPY package.json ./
RUN npm install

# Copy all source files
COPY . ./

# Build the TypeScript project
RUN npm run build

# Set production environment
ENV NODE_ENV=production

# Expose default command to start the MCP server
CMD ["node", "dist/index.js"]
